num_func = int(777)
quant_hr = input("Informe a quantidade de horas trabalhadas: ")
valor_hr = input("Informe o valor do salário por hora trabalhada: ")
print("NUMBER =", num_func)
print("SALARY =", "U$", "{:.2f}".format(int(quant_hr)*float(valor_hr)))
